# rubocop:disable Metrics/BlockLength
desc "Update EU ExportHealthCertificate paths to general licence path"
task update_export_health_certificate_paths: :environment do
  paths = [
    "/export-health-certificates/export-porcine-semen-to-the-european-union-certificate-8200",
    "/export-health-certificates/export-in-vitro-produced-bovine-embyos-to-the-european-union-certificate-8201",
    "/export-health-certificates/export-in-vitro-produced-bovine-embryos-using-semen-from-approved-centres-to-the-european-union-certificate-8202",
    "/export-health-certificates/export-in-vivo-derived-bovine-embryos-to-the-european-union-certificate-8203",
    "/export-health-certificates/export-equine-semen-from-an-approved-collection-centre-collected-after-30-09-2014-to-the-european-union-certificate-8204",
    "/export-health-certificates/export-equine-semen-from-an-approved-collection-centre-collected-between-01-09-2010-and-30-09-2014-to-the-european-union-certificate-8205",
    "/export-health-certificates/export-equine-semen-from-an-approved-collection-centre-collected-before-01-09-2010-to-the-european-union-certificate-8206",
    "/export-health-certificates/export-equine-semen-from-an-approved-semen-storage-centre-to-the-european-union-certificate-8207",
    "/export-health-certificates/export-ovine-and-caprine-ova-and-embryos-to-the-european-union-certificate-8208",
    "/export-health-certificates/export-ovine-and-caprine-semen-from-a-collection-centre-to-the-european-union-certificate-8209",
    "/export-health-certificates/export-ovine-and-caprine-semen-from-a-storage-centre-to-the-european-union-certificate-8210",
    "/export-health-certificates/export-bovine-semen-from-a-storage-centre-to-the-european-union-certificate-8211",
    "/export-health-certificates/export-bovine-semen-from-a-collection-centre-to-the-european-union-certificate-8212",
    "/export-health-certificates/export-bovine-semen-collected-processed-and-stored-before-31-12-2004-from-a-collection-centre-to-the-european-union-certificate-8213",
    "/export-health-certificates/export-equine-ova-and-embryos-collected-or-produced-after-30-09-2014-to-the-european-union-certificate-8214",
    "/export-health-certificates/export-equine-ova-and-embryos-collected-processed-and-stored-after-31-08-2010-and-before-01-10-2014-to-the-european-union-certificate-8215",
    "/export-health-certificates/export-pet-birds-to-the-european-union-certificate-8217",
    "/export-health-certificates/export-dogs-cats-and-ferrets-for-commercial-purposes-to-the-european-union-certificate-8218",
    "/export-health-certificates/export-domestic-porcine-animals-intended-for-immediate-slaughter-to-the-european-union-certificate-8219",
    "/export-health-certificates/export-domestic-ovine-and-caprine-animals-intended-for-breeding-or-production-to-the-european-union-certificate-8220",
    "/export-health-certificates/export-domestic-ovine-and-caprine-animals-intended-for-immediate-slaughter-to-the-european-union-certificate-8221",
    "/export-health-certificates/export-rhinoceroses-elephants-and-certain-even-toed-ungulates-to-the-european-union-certificate-8222",
    "/export-health-certificates/export-domestic-bovine-animals-intended-for-breeding-or-production-to-the-european-union-certificate-8223",
    "/export-health-certificates/export-domestic-bovine-animals-intended-for-immediate-slaughter-to-the-european-union-certificate-8224",
    "/export-health-certificates/export-animals-of-the-order-artiodactyla-including-bovidae-camelidae-cervidae-giraffidae-moschidae-and-tragulidae-that-are-orginating-from-and-intended-for-an-approved-body-institute-or-centre-to-the-european-union-certifi",
    "/export-health-certificates/export-animals-of-the-order-artiodactyla-including-suidae-tayassuidae-and-hippopotamidae-that-are-orginating-from-and-intended-for-an-approved-body-institute-or-centre-to-the-european-union-certificate-8226",
    "/export-health-certificates/export-animals-of-the-order-perissodactyla-including-tapiridae-and-rhinocerotidae-and-proboscidea-including-elephantidae-that-are-originating-from-and-intended-for-an-approved-body-institute-or-centre-to-the-european-union",
    "/export-health-certificates/export-domestic-porcine-animals-intended-for-breeding-or-production-to-the-european-union-certificate-8228",
    "/export-health-certificates/export-non-domestic-suidae-tayassuidae-and-tapiridae-to-the-european-union-certificate-8229",
    "/export-health-certificates/export-certain-birds-other-than-poultry-to-the-european-union-certificate-8231",
    "/export-health-certificates/export-consignments-of-fewer-than-20-units-of-poultry-hatching-eggs-or-day-old-chicks-to-the-european-union-certificate-8234",
    "/export-health-certificates/export-breeding-or-production-poultry-other-than-ratites-to-the-european-union-certificate-8235",
    "/export-health-certificates/export-breeding-or-productive-ratites-to-the-european-union-certificate-8236",
    "/export-health-certificates/export-day-old-chicks-other-than-of-ratites-to-the-european-union-certificate-8237",
    "/export-health-certificates/export-day-old-chicks-of-ratites-to-the-european-union-certificate-8238",
    "/export-health-certificates/export-slaughter-poultry-and-poultry-for-restocking-game-supplies-other-than-ratites-to-the-european-union-certificate-8239",
    "/export-health-certificates/export-ratites-for-slaughter-to-the-european-union-certificate-8240",
    "/export-health-certificates/export-the-meat-of-farmed-rabbits-to-the-european-union-certificate-8245",
    "/export-health-certificates/export-the-meat-of-wild-rabbits-and-hares-to-the-european-union-certificate-8246",
    "/export-health-certificates/export-the-meat-of-wild-land-mammals-other-than-ungulates-and-leporidae-to-the-european-union-certificate-8247",
    "/export-health-certificates/export-live-bivalve-molluscs-echinoderms-tunicates-and-marine-gastropods-intended-for-human-consumption-to-the-european-union-certificate-8249",
    "/export-health-certificates/export-live-bivalve-molluscs-echinoderms-tunicates-and-marine-gastropods-intended-for-human-consumption-to-the-eu-certificate-8249",
    "/export-health-certificates/export-and-store-live-aquaculture-animals-fish-eggs-and-uneviscerated-fish-intended-for-human-consumption-to-the-european-union-certificate-8250",
    "/export-health-certificates/transit-and-storage-of-live-aquaculture-animals-fish-eggs-and-uneviscerated-fish-intended-for-human-consumption-to-the-eu-for-onward-shipment-outside-the-eu-certificate-8250",
    "/export-health-certificates/export-animal-casings-to-the-european-union-certificate-8252",
    "/export-health-certificates/export-animal-casings-for-transit-through-or-storage-in-the-european-union-certificate-8253",
    "/export-health-certificates/export-certain-meat-products-and-treated-stomachs-bladders-and-intestines-to-the-european-union-certificate-8254",
    "/export-health-certificates/export-certain-meat-products-and-treated-stomachs-bladders-and-intestines-for-transit-through-or-storage-in-the-european-union-certificate-8255",
    "/export-health-certificates/export-meat-preparations-intended-for-transit-through-or-storage-in-the-european-union-certificate-8256",
    "/export-health-certificates/export-meat-preparations-to-the-european-union-certificate-8257",
    "/export-health-certificates/export-fresh-meat-including-minced-meat-of-domestic-porcine-animals-to-the-european-union-certificate-8260",
    "/export-health-certificates/export-fresh-meat-including-minced-meat-of-domestic-bovine-animals-to-the-european-union-certificate-8261",
    "/export-health-certificates/export-fresh-meat-of-domestic-ovine-animals-and-caprine-animals-to-the-european-union-certificate-8262",
    "/export-health-certificates/export-fresh-meat-including-minced-meat-for-transit-through-or-storage-in-the-european-union-certificate-8263",
    "/export-health-certificates/export-fresh-meat-excluding-offal-and-minced-meat-of-farmed-non-domestic-animals-belonging-to-the-suidae-tayassuidae-or-tapiridae-families-certificate-8265",
    "/export-health-certificates/export-fresh-meat-excluding-offal-and-minced-meat-of-wild-non-domestic-animals-of-the-order-artiodactyla-excluding-bovines-sheep-goats-and-pigs-and-of-the-families-rhinocerotidae-and-elephantidae-to-the-european-union-cert",
    "/export-health-certificates/export-fresh-meat-excluding-offal-and-minced-meat-of-wild-non-domestic-animals-belonging-to-the-suidae-tayassuidae-or-tapiridae-families-to-the-european-union-certificate-8268",
    "/export-health-certificates/export-fresh-meat-excluding-offal-and-minced-meat-of-farmed-non-domestic-rhinoceroses-elephants-and-certain-even-toed-ungulates-to-the-european-union-certificate-8269",
    "/export-health-certificates/export-fishery-products-intended-for-human-consumption-to-the-european-union-certificate-8270",
    "/export-health-certificates/export-fishery-products-intended-for-human-consumption-to-the-eu-certificate-8270",
    "/export-health-certificates/export-chilled-frozen-or-prepared-frogs-legs-intended-for-human-consumption-to-the-european-union-certificate-8271",
    "/export-health-certificates/export-honey-royal-jelly-and-other-apiculture-products-intended-for-human-consumption-to-the-european-union-certificate-8272",
    "/export-health-certificates/export-highly-refined-chondroitin-sulphate-hyaluronic-acid-other-hydrolysed-cartilage-products-chitosan-glucosamine-rennet-isinglass-and-amino-acids-intended-for-human-consumption-to-the-european-union-certificate-8273",
    "/export-health-certificates/export-chilled-frozen-shelled-cooked-prepared-or-preserved-snails-intended-for-human-consumption-to-the-european-union-certificate-8274",
    "/export-health-certificates/export-materials-for-production-of-gelatine-or-collagen-for-human-consumption-to-transit-through-the-european-union-certificate-8275",
    "/export-health-certificates/export-collagen-intended-for-human-consumption-to-the-european-union-certificate-8276",
    "/export-health-certificates/export-gelatine-intended-for-human-consumption-to-the-european-union-certificate-8277",
    "/export-health-certificates/export-raw-materials-for-the-production-of-gelatine-and-collagen-intended-for-human-consumption-to-the-european-union-certificate-8278",
    "/export-health-certificates/export-treated-raw-materials-for-the-production-of-gelatine-and-collagen-intended-for-human-consumption-to-the-european-union-certificate-8279",
    "/export-health-certificates/export-colostrum-and-colostrum-based-products-of-cows-ewes-goats-and-buffaloes-for-human-consumption-to-the-european-union-certificate-8280",
    "/export-health-certificates/export-composite-food-products-intended-for-human-consumption-to-the-european-union-certificate-8281",
    "/export-health-certificates/export-composite-food-products-intended-for-human-consumption-for-transit-through-or-storage-in-the-european-union-certificate-8282",
    "/export-health-certificates/export-raw-milk-dairy-products-colostrum-and-colostrum-based-products-for-human-consumption-intended-for-transit-through-or-storage-in-the-european-union-certificate-8283",
    "/export-health-certificates/export-dairy-products-for-human-consumption-to-the-european-union-certificate-8284",
    "/export-health-certificates/export-dairy-products-derived-from-milk-of-cows-ewes-goats-and-buffaloes-for-human-consumption-to-the-european-union-certificate-8285",
    "/export-health-certificates/export-raw-milk-and-dairy-products-intended-for-further-processing-in-the-european-union-before-being-used-for-human-consumption-certificate-8286",
    "/export-health-certificates/export-of-dairy-products-made-from-raw-milk-for-human-consumption-to-the-european-union-certificate-8287",
    "/export-health-certificates/export-specified-pathogen-free-spf-eggs-to-the-european-union-certificate-8289",
    "/export-health-certificates/export-avian-derived-commodities-for-transit-through-or-storage-in-the-european-union-including-specified-pathogen-free-eggs-meat-minced-meat-and-mechanically-separated-meat-of-poultry-ratites-and-wild-game-birds-eggs-and-",
    "/export-health-certificates/export-wild-game-bird-meat-to-the-european-union-certificate-8291",
    "/export-health-certificates/export-egg-products-to-the-european-union-certificate-8292",
    "/export-health-certificates/export-eggs-for-human-consumption-to-the-european-union-certificate-8293",
    "/export-health-certificates/export-hatching-eggs-of-poultry-to-or-transit-through-the-european-union-certificate-8294",
    "/export-health-certificates/export-hatching-eggs-of-ratites-to-or-transit-through-the-european-union-certificate-8295",
    "/export-health-certificates/export-poultry-meat-to-the-european-union-certificate-8296",
    "/export-health-certificates/export-meat-of-farmed-ratites-for-human-consumption-to-the-european-union-certificate-8297",
    "/export-health-certificates/export-blood-products-not-intended-for-human-consumption-that-could-be-used-as-feed-material-intended-for-dispatch-to-or-transit-through-the-european-union-certificate-8299",
    "/export-health-certificates/export-processed-animal-protein-pap-from-insects-not-intended-for-human-consumption-including-mixtures-and-products-other-than-pet-food-containing-such-protein-to-the-european-union-certificate-8300",
    "/export-health-certificates/export-rendered-fats-not-for-human-consumption-to-be-used-outside-the-feed-chain-to-the-european-union-certificate-8301",
    "/export-health-certificates/export-of-gelatine-and-collagen-not-for-human-consumption-to-be-used-as-feed-material-or-outside-the-feed-chain-to-the-european-union-certificate-8302",
    "/export-health-certificates/export-of-fat-derivatives-not-intended-for-human-consumption-to-be-used-as-feed-or-outside-the-feed-chain-to-the-european-union-certificate-8303",
    "/export-health-certificates/export-of-egg-products-not-intended-for-human-consumption-that-could-be-used-as-feed-material-to-the-european-union-certificate-8304",
    "/export-health-certificates/export-processed-pet-food-other-than-canned-pet-food-to-or-transit-through-the-european-union-certificate-8305",
    "/export-health-certificates/export-raw-pet-food-for-direct-sale-or-animal-by-products-to-be-fed-to-fur-animals-to-or-transit-through-the-european-union-certificate-8306",
    "/export-health-certificates/export-blood-and-blood-products-from-equidae-to-be-used-outside-the-feed-chain-to-or-transit-through-the-european-union-certificate-8307",
    "/export-health-certificates/export-untreated-blood-products-for-the-manufacture-of-derived-products-for-purposes-outside-the-feed-chain-for-farmed-animals-to-or-transit-through-the-european-union-certificate-8308",
    "/export-health-certificates/export-treated-blood-products-excluding-of-equidae-for-the-manufacture-of-derived-products-for-purposes-outside-the-feed-chain-for-farmed-animals-intended-for-dispatch-to-or-transit-through-the-european-union-certificate-8",
    "/export-health-certificates/export-treated-game-trophies-and-other-preparations-of-birds-and-ungulates-to-or-transit-through-the-european-union-certificate-8310",
    "/export-health-certificates/export-animal-by-products-for-the-manufacture-of-pet-food-to-or-transit-through-the-european-union-certificate-8311",
    "/export-health-certificates/export-animal-by-products-for-purposes-outside-the-feed-chain-or-for-trade-samples-to-or-transit-through-the-european-union-certificate-8312",
    "/export-health-certificates/export-rendered-fats-not-for-human-consumption-to-be-used-as-feed-material-to-or-transit-through-the-european-union-certificate-8314",
    "/export-health-certificates/export-hydrolysed-protein-dicalcium-phosphate-and-tricalcium-phosphate-to-or-transit-through-the-european-union-certificate-8315",
    "/export-health-certificates/export-apiculture-products-intended-exclusively-for-use-in-apiculture-to-or-through-the-european-union-certificate-8317",
    "/export-health-certificates/export-fat-derivatives-not-intended-for-human-consumption-to-be-used-outside-the-feed-chain-to-or-transit-through-the-european-union-certificate-8318",
    "/export-health-certificates/export-processed-manure-derived-products-from-processed-manure-and-guano-from-bats-to-or-transit-through-the-european-union-certificate-8319",
    "/export-health-certificates/export-horns-and-hoof-products-to-produce-fertiliser-to-or-transit-through-the-european-union-certificate-8320",
    "/export-health-certificates/export-gelatine-to-be-used-by-the-photographic-industry-to-the-european-union-certificate-8321",
    "/export-health-certificates/export-milk-milk-based-products-and-milk-derived-products-not-intended-for-human-consumption-to-the-european-union-certificate-8322",
    "/export-health-certificates/export-bovine-colostrum-and-bovine-colostrum-products-not-intended-for-human-consumption-to-the-european-union-certificate-8323",
    "/export-health-certificates/export-canned-pet-food-to-or-transit-through-the-european-union-certificate-8324",
    "/export-health-certificates/export-dog-chews-to-the-european-union-certificate-8325",
    "/export-health-certificates/export-flavouring-innards-for-use-in-the-manufacture-of-pet-food-to-the-european-union-certificate-8326",
    "/export-health-certificates/export-fresh-or-chilled-hides-and-skins-of-ungulates-to-the-european-union-certificate-8327",
    "/export-health-certificates/export-treated-hides-and-skins-of-ungulates-to-or-transit-through-the-european-union-certificate-8328",
    "/export-health-certificates/export-treated-hides-and-skins-of-ruminants-and-equidae-that-have-been-separated-for-21-days-to-the-european-union-certificate-8329",
    "/export-health-certificates/export-of-game-trophies-or-other-preparations-of-birds-and-ungulates-to-the-european-union-certificate-8330",
    "/export-health-certificates/export-pig-bristles-from-third-countries-free-from-african-swine-fever-to-the-european-union-certificate-8331",
    "/export-health-certificates/export-fish-oil-not-intended-for-human-consumption-to-or-transit-through-the-european-union-certificate-8332",
    "/export-health-certificates/export-processed-animal-protein-pap-other-than-types-derived-from-farmed-insects-to-the-european-union-certificate-8333",
    "/export-health-certificates/movement-back-to-the-european-union-of-registered-horses-for-racing-competition-and-cultural-events-after-temporary-import-to-the-uk-for-a-period-of-less-than-30-days-certificate-8334",
    "/export-health-certificates/permanently-export-an-equine-animal-for-breeding-or-production-to-the-european-union-certificate-8335",
    "/export-health-certificates/temporarily-export-a-registered-horse-for-a-period-of-less-than-90-days-to-the-european-union-certificate-8336",
    "/export-health-certificates/export-a-live-equine-animal-destined-for-another-third-country-which-will-transit-the-european-union-certificate-8337",
    "/export-health-certificates/export-wild-leporidae-farmed-rabbits-and-wild-land-mammals-other-than-ungulates-for-the-transit-through-or-storage-in-the-european-union-certificate-8339",
    "/export-health-certificates/export-intermediate-products-to-be-used-for-the-manufacture-of-medicinal-and-cosmetic-products-intended-for-dispatch-to-or-for-transit-through-the-european-union-certificate-8341",
    "/export-health-certificates/export-bone-horn-and-hoof-products-excluding-meal-intended-for-use-other-than-as-feed-material-organic-fertilisers-or-soil-improvers-for-dispatch-to-or-for-transit-through-the-european-union-certificate-8342",
    "/export-health-certificates/export-untreated-wool-and-hair-to-the-european-union-certificate-8343",
  ]
  content_ids = []
  redirect_path = "/starting-to-export/licences"

  paths.each do |path|
    unpublishing = Edition.live.find_by(base_path: path).unpublishing
    redirect_details = [{
                      "path"        =>  path,
                      "type"        =>  "exact",
                      "destination" =>  redirect_path,

                    }]
    unpublishing.redirects = redirect_details
    unpublishing.type = "redirect"
    unpublishing.save!

    content_ids << unpublishing.edition.content_id
  end

  Commands::V2::RepresentDownstream.new.call(content_ids, queue: DownstreamQueue::HIGH_QUEUE)
end
# rubocop:enable Metrics/BlockLength
