#!/usr/bin/env ruby

require "English"

def usage
  abort("Usage:\n\t#{$PROGRAM_NAME} a_checker_script")
end

check = ARGV.fetch(0) { usage }

base_paths_file_path = "tmp/base_paths/filtered_base_paths"
base_paths = File.read(base_paths_file_path).split("\n")
total_base_paths = base_paths.count

output_file = File.open("output.txt", "w")

base_paths.each_with_index do |base_path, index|
  info = "#{index + 1}/#{total_base_paths}: #{base_path}"
  puts "Processing #{info}"
  result = `#{check} #{base_path}`
  success = $CHILD_STATUS.success?

  unless success
    output_file.write(result)
  end

  puts "Processed #{info}\n\n"
  puts
end

output_file.close
