#!/usr/bin/env bash

# Start Content Store, Publishing API, Static, and the relevant frontend app
# before running this script

script/live_content/bulk_check "script/live_content/diff_frontend" --less
