#!/usr/bin/env ruby

# Start Content Store, Publishing API, Static, and the relevant frontend app
# before running this script

require "English"
require "fileutils"
require "json"
require "net/http"
require "uri"

# For a given base path, request the frontend page with Content Store and
# Publishing API's GraphQL endpoint as the data source and diff the results.

OUTPUT_DIR = "tmp/diffs/frontend".freeze

FileUtils.mkdir_p(OUTPUT_DIR)

def usage
  abort("Usage:\n\t#{$PROGRAM_NAME} a_base_path")
end

BASE_PATH = ARGV.fetch(0) { usage }

def rendering_app
  graphql_query = <<~QUERY
    {
      edition(base_path: "#{BASE_PATH}", content_store: "live") {
        ...on Edition { rendering_app }
      }
    }
  QUERY

  response = Net::HTTP.post_form(
    URI("http://publishing-api.dev.gov.uk/graphql"),
    query: graphql_query,
  )

  JSON.parse(response.body).dig("data", "edition", "rendering_app")
end

def uri(with_graphql:)
  domain = "http://#{rendering_app}.dev.gov.uk"
  URI("#{domain}#{BASE_PATH}?graphql=#{with_graphql}")
end

content_store_uri = uri(with_graphql: false)
publishing_api_uri = uri(with_graphql: true)

def get_html(uri)
  response = Net::HTTP.get_response(uri)

  if response.code.to_i >= 400
    abort(
      <<~MESSAGE,
        Aborting due to failed request
        URI: #{uri}
        Code: #{response.code}
      MESSAGE
    )
  end

  response.body
end

def normalise_html(html)
  html
    .gsub(/\?graphql=(true|false)/, "")
    .gsub(/nonce="[^"]{22}=="/, 'nonce="HASH=="')
    .gsub(
      /( aria-labelledby="[^ ]+-)[a-z0-9]{8}( [^"]+-)[a-z0-9]{8}"/,
      '\1HASH\2HASH',
    )
    .gsub(
      / (aria-labelledby|data-controls|for|id)(="[^"]+-)[a-z0-9]{8}"/,
      ' \1\2HASH"',
    )
    .gsub(/\n *<meta name="govuk:content-has-history" content="[^"]+">/, "")
    .gsub(
      /(<meta name=")(csrf-token|csp-nonce|govuk:updated-at)(" content=")[^"]+"(?: \/)?>/,
      '\1\2\3CONTENT">',
    )
    .gsub(
      /(datetime=)(?:"|&quot;)(\d{4}-\d{2}-\d{2})[ T]\d{2}(:\d{2}:\d{2})[ Z]?(?:UTC|\+00:00|\+01:00)?(?:"|&quot;)/,
      '\1"\2 HH\3"',
    )
end

content_store_html = normalise_html(get_html(content_store_uri)).force_encoding("UTF-8")
publishing_api_html = normalise_html(get_html(publishing_api_uri)).force_encoding("UTF-8")

content_store_file_path = File.join(OUTPUT_DIR, "content_store_response.html")
publishing_api_file_path = File.join(OUTPUT_DIR, "publishing_api_response.html")

File.write(content_store_file_path, content_store_html)
File.write(publishing_api_file_path, publishing_api_html)

puts `git diff --no-index --word-diff=color #{content_store_file_path} #{publishing_api_file_path}`

exit $CHILD_STATUS.exitstatus
