#!/usr/bin/env ruby

# Start Content Store, Publishing API, Static, and the relevant frontend app
# before running this script

require "English"
require "fileutils"
require "json"
require "net/http"
require "uri"

# For a given base path, request the frontend page with Content Store and
# Publishing API's GraphQL endpoint as the data source and diff the results.

OUTPUT_DIR = "tmp/diffs/frontend".freeze

FileUtils.mkdir_p(OUTPUT_DIR)

def usage
  abort("Usage:\n\t#{$PROGRAM_NAME} a_base_path")
end

BASE_PATH = ARGV.fetch(0) { usage }
RENDERING_APP = begin
  graphql_query = <<~QUERY
    {
      edition(base_path: "#{BASE_PATH}", content_store: "live") {
        ...on Edition { rendering_app }
      }
    }
  QUERY

  publishing_api_host = ENV.fetch("PUBLISHING_API_HOST", "publishing-api.dev.gov.uk")
  response = Net::HTTP.post_form(
    URI("http://#{publishing_api_host}/graphql"),
    query: graphql_query,
  )

  JSON.parse(response.body).dig("data", "edition", "rendering_app")
end

def uri(with_graphql:)
  host = ENV.fetch(
    "#{RENDERING_APP.upcase.gsub('-', '_')}_HOST",
    "#{RENDERING_APP}.dev.gov.uk",
  )

  URI("http://#{host}#{BASE_PATH}?graphql=#{with_graphql}")
end

uri_without_graphql = uri(with_graphql: false)
uri_with_graphql = uri(with_graphql: true)

def get_html(uri)
  response = Net::HTTP.get_response(uri)

  if response.code.to_i >= 400
    abort(
      <<~MESSAGE,
        Aborting due to failed request
        URI: #{uri}
        Code: #{response.code}
      MESSAGE
    )
  end

  response.body
end

def normalise_html(html)
  html
    .gsub(/\?graphql=(true|false)/, "")
    .gsub(/nonce="[^"]{22}=="/, 'nonce="HASH=="')
    .gsub(/value="[a-zA-Z0-9_-]{86}"/, 'value="HASH"')
    .gsub(
      /( aria-labelledby="[^ ]+-)[a-z0-9]{8}( [^"]+-)[a-z0-9]{8}"/,
      '\1HASH\2HASH',
    )
    .gsub(
      / (aria-describedby|aria-labelledby|data-aria-controls|data-controls|for|id)(="[^"]+-)[a-z0-9]{8}(-?[^"]*)"/,
      ' \1\2HASH\3"',
    )
    .gsub(/\n *<meta name="govuk:content-has-history" content="[^"]+">/, "")
    .gsub(
      /(<meta name=")(csrf-token|csp-nonce|govuk:updated-at)(" content=")[^"]+"(?: \/)?>/,
      '\1\2\3CONTENT">',
    )
    .gsub(
      /(datetime=)(?:"|&quot;)(\d{4}-\d{2}-\d{2})[ T]\d{2}(:\d{2}:\d{2})[ Z]?(?:UTC|\+00:00|\+01:00)?(?:"|&quot;)/,
      '\1"\2 HH\3"',
    )
    .gsub(/\\u003c.+--\\u003e/, "")
end

html_without_graphql = normalise_html(get_html(uri_without_graphql)).force_encoding("UTF-8")
html_with_graphql = normalise_html(get_html(uri_with_graphql)).force_encoding("UTF-8")

without_graphql_file_path = File.join(OUTPUT_DIR, "without_graphql_response.html")
with_graphql_file_path = File.join(OUTPUT_DIR, "with_graphql_response.html")

File.write(without_graphql_file_path, html_without_graphql)
File.write(with_graphql_file_path, html_with_graphql)

puts `git diff --no-index --word-diff=color #{without_graphql_file_path} #{with_graphql_file_path}`

exit $CHILD_STATUS.exitstatus
