@startuml

hide circle
hide empty fields
hide empty methods

class Document
class Edition
class PathReservation

package "Dependencies" {
  class LinkSet
  class Link
}

package "Event Log" {
  class Event
}

package "Access Control" {
  class AccessLimit
  class User
}

Edition <-- LinkSet
Edition <-up- Link
LinkSet *--> Link

Edition <-down- AccessLimit
AccessLimit o--> User

Document <-- Edition

@enduml
