#!/usr/bin/env ruby

query_values = [
  { with_drafts: true, default_root_locale: true},
  { with_drafts: true, default_root_locale: false},
  { with_drafts: false, default_root_locale: true},
  { with_drafts: false, default_root_locale: false},
]

link_kind_values = %w[link_set edition]

# state, withdawal, permitted unpublished link type
state_values = [
  ["draft", nil, nil],
  ["published", nil, nil],
  ["unpublished", true, true],
  ["unpublished", true, false],
  ["unpublished", false, true],
  ["unpublished", false, false],
]

renderable_document_type_values = [false, true]
locale_values = %w[default fr hu]

edition_values = link_kind_values.product(
  state_values,
  renderable_document_type_values,
  locale_values,
).map do
  {
    link_kind: _1,
    state: _2[0],
    withdrawal: _2[1],
    permitted_unpublished_link_type: _2[2],
    renderable_document_type: _3,
    locale: _4,
  }
end

test_cases = query_values.product(edition_values.combination(2).to_a)
  .map { { **_1, linked_editions: _2 } }

def fields_equal(a, b, *fields) # rubocop:disable Naming/MethodParameterName
  fields.all? { a[it] == b[it] }
end

test_cases.reject! do |test_case|
  [
    # We only need the following cases.
    # root_locale: "default", locale: "default"
    # root_locale: "default", locale: "fr"
    # root_locale: "fr", locale: "default"
    # root_locale: "fr", locale: "fr"
    # root_locale: "fr", locale: "hu"
    test_case[:default_root_locale] && test_case[:linked_editions].any? {it[:locale] == "hu"},

    # A single document can't be in the live content store twice with different
    # states. The two test cases are the same document if they have the same
    # locale, because we already assume that they have the same Content ID.
    if fields_equal(*test_case[:linked_editions], :locale)
      test_case[:linked_editions].map { it[:state] }.sort == %w[published unpublished]
    else
      false
    end
  ].any?
end

# 6728
puts test_cases.count
puts test_cases.first.inspect
