---
:verbose: false
:concurrency: 12
<% if ENV.key?('SIDEKIQ_LOGFILE') %>
:logfile: <%= ENV['SIDEKIQ_LOGFILE'] %>
<% end %>
:queues:
  - downstream_high
  - dependency_resolution
  - downstream_low
  - experiments
  - default
  - import
:scheduler:
  :schedule:
    UpdateStatisticsCachesJob:
      cron: '30 2 * * *' # Runs at 2:30 a.m every day
