---
:verbose: false
:concurrency: 12
<% if ENV.key?('SIDEKIQ_LOGFILE') %>
:logfile: <%= ENV['SIDEKIQ_LOGFILE'] %>
<% end %>
:queues:
  - downstream_high
  - dependency_resolution
  - downstream_low
  - experiments
  - default
  - import
