---
:verbose: true
:concurrency:  2
:logfile: ./log/sidekiq.json.log
:queues:
  - content_store_high
  - content_store_low
  - downstream_high
  - downstream_low
  - dependency_resolution
  - experiments
  - default
