@startuml

hide circle
hide empty fields
hide empty methods

class content_id

package "Linking" {
  class LinkSet
  class Link
}

package "History" {
  class Event
  class Action
}

package "Content" {
  class Document
  class Edition
  class Unpublishing
  class ChangeNote
  class AccessLimit
  class PathReservation
}

Document -up-> content_id
LinkSet -up-> content_id
Event -up-> content_id
Action -up-> content_id
Document *-down- Edition
LinkSet *-right- Link
ChangeNote -up-> Edition

AccessLimit -up-> Edition
Unpublishing -up-> Edition
Action -> Edition
Link .> content_id

@enduml
