#!/usr/bin/env ruby

$LOAD_PATH << File.expand_path("../", File.dirname(__FILE__))

require "config/environment"

def usage_and_abort
  abort("Usage:\n\t#{$PROGRAM_NAME} a_schema_name")
end

def validate_schema_name!(schema_name)
  GovukSchemas::Schema.find(publisher_schema: schema_name)
rescue Errno::ENOENT
  usage_and_abort
end

def validate_template_file_uniqueness!(template_filename)
  if File.exist?(template_filename)
    warn("Error: a file already exists (#{template_filename}) for the GraphQL query you're attempting to build")
    usage_and_abort
  end
end

schema_name = ARGV[0]

validate_schema_name!(schema_name)

template_filename = "app/graphql/queries/#{schema_name}.graphql.erb"
validate_template_file_uniqueness!(template_filename)

query_builder = GraphqlQueryBuilder.new(schema_name)
query = query_builder.build_query

File.open(template_filename, "w") { |f| f.puts(query) }

puts("👍")
