#!/usr/bin/env ruby

$LOAD_PATH << File.expand_path(".")
require "config/environment"

def usage
  abort("Usage:\n\t#{$PROGRAM_NAME} one_schema_name or_more_schema_names")
end

schema_names = ARGV

usage if schema_names.empty?

MIN_PUBLISHED_PER_SCHEMA_NAME = 2000
MIN_PUBLISHED_PER_DOCUMENT_TYPE = 250

data = schema_names.flat_map do |schema_name|
  puts "\nSchema name: #{schema_name}"

  document_types = GovukSchemas::Schema
    .find(frontend_schema: schema_name)
    .dig("properties", "document_type", "enum")

  document_types.flat_map do |document_type|
    puts "\nDocument type: #{document_type}"

    data = Edition
      .live
      .joins(:document)
      .where(schema_name:, document_type:)
      .where.not(state: "unpublished")
      .pluck(:base_path, :content_id, :locale)

    # it would be quicker to use a limit before the pluck, but then we'd get a
    # less random sample
    data.sample([
      MIN_PUBLISHED_PER_SCHEMA_NAME / document_types.size,
      MIN_PUBLISHED_PER_DOCUMENT_TYPE,
    ].max).tap do |sample|
      puts "Sampling #{sample.size} of #{data.size} published editions"
    end
  end
end

File.write(
  "script/data/sample",
  data.map { _1.join(",") }.join("\n"),
)

File.write(
  "script/data/sample_base_paths",
  data.map(&:first).join("\n"),
)
