#!/usr/bin/env ruby

$LOAD_PATH << File.expand_path(".")
require "config/environment"

def usage
  abort("Usage:\n\t#{$PROGRAM_NAME} one_schema_name or_more_schema_names")
end

schema_names = ARGV

usage if schema_names.empty?

MIN_PUBLISHED_PER_SCHEMA_NAME = 2000
MIN_PUBLISHED_PER_DOCUMENT_TYPE = 250
SAMPLE_FIELDS = %i[base_path content_id locale schema_name document_type].freeze

# it might be quicker to use limit before pluck, but then we'd get a less random
# sample (database-level random ordering is slow given the size of the table)

def published_sample(schema_name:, document_type:, document_type_count:)
  data = Edition
    .with_document
    .live
    .where(schema_name:, document_type:)
    .where.not(state: "unpublished")
    .pluck(*SAMPLE_FIELDS)

  data.sample([
    MIN_PUBLISHED_PER_SCHEMA_NAME / document_type_count,
    MIN_PUBLISHED_PER_DOCUMENT_TYPE,
  ].max).tap do |sample|
    puts "Sampling #{sample.size} of #{data.size} published editions"
  end
end

def withdrawn_sample(schema_name:, document_type:)
  data = Edition
    .with_document
    .with_unpublishing
    .live
    .where(
      schema_name:,
      document_type:,
      state: "unpublished",
      unpublishing: { type: "withdrawal" },
    )
    .pluck(*SAMPLE_FIELDS)

  data.sample(25).tap do |sample|
    puts "Sampling #{sample.size} of #{data.size} withdrawn editions"
  end
end

data = schema_names.flat_map do |schema_name|
  puts "\nSchema name: #{schema_name}"

  document_types = GovukSchemas::Schema
    .find(frontend_schema: schema_name)
    .dig("properties", "document_type", "enum")

  document_types.flat_map do |document_type|
    puts "\nDocument type: #{document_type}"

    [
      published_sample(
        schema_name:,
        document_type:,
        document_type_count: document_types.size,
      ),
      withdrawn_sample(schema_name:, document_type:),
    ].flatten(1)
  end
end

File.write(
  "script/data/sample",
  data.map { _1.join(",") }.join("\n"),
)

File.write(
  "script/data/sample_base_paths",
  data.map(&:first).join("\n"),
)
