name: Test Content Schemas (1)

on:
  workflow_dispatch: {}
  push:
    branches:
      - main
    paths:
      - "content_schemas/**"
  pull_request:
    paths:
      - "content_schemas/**"

jobs:
  all-jobs-completed:
    name: All jobs completed
    runs-on: ubuntu-latest
    needs: [test-collections-publisher, test-collections, test-contacts-admin, test-content-data-api, test-content-publisher, test-content-store, test-content-tagger, test-email-alert-frontend, test-email-alert-service, test-feedback, test-finder-frontend, test-frontend, test-government-frontend, test-hmrc-manuals-api]
    steps:
      - run: 'echo "All content schema tests completed." '

  test-collections-publisher:
    name: Test Collections Publisher
    uses: alphagov/collections-publisher/.github/workflows/rspec.yml@main
    with:
      ref: 'main'
      publishingApiRef: ${{ github.ref }}

  test-collections:
    name: Test Collections
    uses: alphagov/collections/.github/workflows/rspec.yml@main
    with:
      ref: 'main'
      publishingApiRef: ${{ github.ref }}

  test-contacts-admin:
    name: Test Contacts Admin
    uses: alphagov/contacts-admin/.github/workflows/rspec.yml@main
    with:
      ref: 'main'
      publishingApiRef: ${{ github.ref }}

  test-content-data-api:
    name: Test Content Data API
    uses: alphagov/content-data-api/.github/workflows/rspec.yml@main
    with:
      ref: 'main'
      publishingApiRef: ${{ github.ref }}

  test-content-publisher:
    name: Test Content Publisher
    uses: alphagov/content-publisher/.github/workflows/rspec.yml@main
    with:
      ref: 'main'
      publishingApiRef: ${{ github.ref }}

  test-content-store:
    name: Test Content Store
    uses: alphagov/content-store/.github/workflows/rspec.yml@main
    with:
      ref: 'main'
      publishingApiRef: ${{ github.ref }}

  test-content-tagger:
    name: Test Content Tagger
    uses: alphagov/content-tagger/.github/workflows/rspec.yml@main
    with:
      ref: 'main'
      publishingApiRef: ${{ github.ref }}

  test-email-alert-frontend:
    name: Test Email Alert Frontend
    uses: alphagov/email-alert-frontend/.github/workflows/rspec.yml@main
    with:
      ref: 'main'
      publishingApiRef: ${{ github.ref }}

  test-email-alert-service:
    name: Test Email Alert Service
    uses: alphagov/email-alert-service/.github/workflows/rspec.yml@main
    with:
      ref: 'main'
      publishingApiRef: ${{ github.ref }}

  test-feedback:
    name: Test Feedback
    uses: alphagov/feedback/.github/workflows/rspec.yml@main
    with:
      ref: 'main'
      publishingApiRef: ${{ github.ref }}

  test-finder-frontend:
    name: Test Finder Frontend
    uses: alphagov/finder-frontend/.github/workflows/rspec.yml@main
    with:
      ref: 'main'
      publishingApiRef: ${{ github.ref }}

  test-frontend:
    name: Test Frontend
    uses: alphagov/frontend/.github/workflows/rspec.yml@main
    with:
      ref: 'main'
      publishingApiRef: ${{ github.ref }}

  test-government-frontend:
    name: Test Government Frontend
    uses: alphagov/government-frontend/.github/workflows/minitest.yml@main
    with:
      ref: 'main'
      publishingApiRef: ${{ github.ref }}

  test-hmrc-manuals-api:
    name: Test HMRC Manuals API
    uses: alphagov/hmrc-manuals-api/.github/workflows/rspec.yml@main
    with:
      ref: 'main'
      publishingApiRef: ${{ github.ref }}
