name: Test Content Schemas (2)

on:
  workflow_dispatch: {}
  push:
    branches:
      - main
    paths:
      - "content_schemas/**"
      - "!content_schemas/README.md"
  pull_request:
    paths:
      - "content_schemas/**"
      - "!content_schemas/README.md"

jobs:
  test-manuals-publisher:
    name: Test Manuals Publisher
    uses: alphagov/manuals-publisher/.github/workflows/rspec.yml@main
    with:
      ref: 'main'
      publishingApiRef: ${{ github.ref }}

  test-search-api:
    name: Test Search API
    uses: alphagov/search-api/.github/workflows/rspec.yml@main
    with:
      ref: 'main'
      publishingApiRef: ${{ github.ref }}
