name: Test Content Schemas (2)

on:
  workflow_dispatch: {}
  push:
    branches:
      - main
    paths:
      - "content_schemas/**"
  pull_request:
    paths:
      - "content_schemas/**"

jobs:
  all-jobs-completed:
    name: All jobs completed
    runs-on: ubuntu-latest
    needs: [test-manuals-publisher, test-publisher, test-search-api, test-search-admin, test-service-manual-publisher, test-short-url-manager, test-smart-answers, test-specialist-publisher, test-travel-advice-publisher, test-whitehall]
    steps:
      - run: 'echo "All content schema tests completed." '

  test-manuals-publisher:
    name: Test Manuals Publisher
    uses: alphagov/manuals-publisher/.github/workflows/rspec.yml@main
    with:
      ref: 'main'
      publishingApiRef: ${{ github.ref }}

  test-publisher:
    name: Test Publisher
    uses: alphagov/publisher/.github/workflows/minitest.yml@main
    with:
      ref: 'main'
      publishingApiRef: ${{ github.ref }}

  test-search-api:
    name: Test Search API
    uses: alphagov/search-api/.github/workflows/rspec.yml@main
    with:
      ref: 'main'
      publishingApiRef: ${{ github.ref }}

  test-search-admin:
    name: Test Search Admin
    uses: alphagov/search-admin/.github/workflows/rspec.yml@main
    with:
      ref: 'main'
      publishingApiRef: ${{ github.ref }}

  test-service-manual-publisher:
    name: Test Service Manual Publisher
    uses: alphagov/service-manual-publisher/.github/workflows/rspec.yml@main
    with:
      ref: 'main'
      publishingApiRef: ${{ github.ref }}

  test-short-url-manager:
    name: Test Short URL Manager
    uses: alphagov/short-url-manager/.github/workflows/rspec.yml@main
    with:
      ref: 'main'
      publishingApiRef: ${{ github.ref }}

  test-smart-answers:
    name: Test Smart Answers
    uses: alphagov/smart-answers/.github/workflows/minitest.yml@main
    with:
      ref: 'main'
      publishingApiRef: ${{ github.ref }}

  test-specialist-publisher:
    name: Test Specialist Publisher
    uses: alphagov/specialist-publisher/.github/workflows/rspec.yml@main
    with:
      ref: 'main'
      publishingApiRef: ${{ github.ref }}

  test-travel-advice-publisher:
    name: Test Travel Advice Publisher
    uses: alphagov/travel-advice-publisher/.github/workflows/rspec.yml@main
    with:
      ref: 'main'
      publishingApiRef: ${{ github.ref }}

  test-whitehall:
    name: Test Whitehall
    uses: alphagov/whitehall/.github/workflows/minitest.yml@main
    with:
      ref: 'main'
      publishingApiRef: ${{ github.ref }}

