name: Test Content Schemas (1)

on:
  workflow_dispatch: {}
  push:
    branches:
      - main
    paths:
      - "content_schemas/**"
      - "!content_schemas/README.md"
  pull_request:
    paths:
      - "content_schemas/**"
      - "!content_schemas/README.md"

jobs:
  test-collections-publisher:
    name: Test Collections Publisher
    uses: alphagov/collections-publisher/.github/workflows/rspec.yml@main
    with:
      ref: 'main'
      publishingApiRef: ${{ github.ref }}

  test-content-data-api:
    name: Test Content Data API
    uses: alphagov/content-data-api/.github/workflows/rspec.yml@main
    with:
      ref: 'main'
      publishingApiRef: ${{ github.ref }}
